import { Geist, Geist_Mono, Caudex } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const caudex = Caudex({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-caudex",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${caudex.className}`}>
      <body
        className={`${caudex.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
